In [1]:
import pandas as pd

# Desafio 1

O objetivo desse projeto é realizar uma análise dos resultados de um evento com os clientes de uma empresa de vendas online. Foi coletado um conjunto de dados que contém os clientes que mais gastaram com produtos dentro de 5 dias de vendas, que é o período de duração do evento. Essa análise vai identificar o cliente com a maior compra na semana, que irá receber um prêmio da loja, e posteriormente, ela pode ajudar a empresa a criar novas estratégias para atrair mais clientes.

In [2]:
#  A base de dados utilizada nessa análise é a dados_vendas_clientes.json e contém informações importantes sobre os clientes como, o nome de cadastro do cliente, o valor total pago na compra e o dia da compra.

#Sabendo essas informações, o desafio do projeto 1: vendas online será abrir a base de dados com Pandas e aplicar o json_normalize.

df_vendas_online = pd.read_json('dados_vendas_clientes.json')
df_vendas_online = pd.json_normalize(df_vendas_online['dados_vendas'])
df_vendas_online

,Data de venda,Cliente,Valor da compra
0,06/06/2022,"[@ANA _LUCIA 321, DieGO ARMANDIU 210, DieGO AR...","[R$ 836,5, R$ 573,33, R$ 392,8, R$ 512,34]"
1,07/06/2022,"[Isabely JOanes 738, Isabely JOanes 738, Isabe...","[R$ 825,31, R$ 168,07, R$ 339,18, R$ 314,69]"
2,08/06/2022,"[Isabely JOanes 738, JOãO Gabriel 671, Julya m...","[R$ 682,05, R$ 386,34, R$ 622,65, R$ 630,79]"
3,09/06/2022,"[Julya meireles 914, MaRIA Julia 444, MaRIA Ju...","[R$ 390,3, R$ 759,16, R$ 334,47, R$ 678,78]"
4,10/06/2022,"[MaRIA Julia 444, PEDRO PASCO 812, Paulo castr...","[R$ 314,24, R$ 311,15, R$ 899,16, R$ 885,24]"

In [3]:
# Etapa 2: 

# Remover os dados em listas dentro do DataFrame;
# Verificar os tipos de dados;
# Identificar colunas numéricas;
# Transformar a coluna numérica para o tipo numérico.

In [4]:
colunas_vendas_online = list(df_vendas_online.columns)
colunas_vendas_online

['Data de venda', 'Cliente', 'Valor da compra']

In [5]:
df_vendas_online = df_vendas_online.explode(colunas_vendas_online[1:])
df_vendas_online.reset_index(drop=True, inplace= True)
df_vendas_online

   Data de venda             Cliente Valor da compra
0     06/06/2022     @ANA _LUCIA 321        R$ 836,5
1     06/06/2022  DieGO ARMANDIU 210       R$ 573,33
2     06/06/2022  DieGO ARMANDIU 210        R$ 392,8
3     06/06/2022  DieGO ARMANDIU 210       R$ 512,34
4     07/06/2022  Isabely JOanes 738       R$ 825,31
5     07/06/2022  Isabely JOanes 738       R$ 168,07
6     07/06/2022  Isabely JOanes 738       R$ 339,18
7     07/06/2022  Isabely JOanes 738       R$ 314,69
8     08/06/2022  Isabely JOanes 738       R$ 682,05
9     08/06/2022    JOãO Gabriel 671       R$ 386,34
10    08/06/2022  Julya meireles 914       R$ 622,65
11    08/06/2022  Julya meireles 914       R$ 630,79
12    09/06/2022  Julya meireles 914        R$ 390,3
13    09/06/2022     MaRIA Julia 444       R$ 759,16
14    09/06/2022     MaRIA Julia 444       R$ 334,47
15    09/06/2022     MaRIA Julia 444       R$ 678,78
16    10/06/2022     MaRIA Julia 444       R$ 314,24
17    10/06/2022     PEDRO PASCO 812       R$ 311,15
18    10/06/2022    Paulo castro 481       R$ 899,16
19    10/06/2022   Thiago fritzz 883       R$ 885,24

In [6]:
df_vendas_online.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     str
 1   Cliente          20 non-null     str
 2   Valor da compra  20 non-null     str
dtypes: str(3)
memory usage: 612.0 bytes

In [7]:
import numpy as np

df_vendas_online['Valor da compra'] = df_vendas_online['Valor da compra'].apply(lambda x: x.replace('R$', '').replace(',', '.').strip())
df_vendas_online['Valor da compra'] = df_vendas_online['Valor da compra'].astype(np.float64)
df_vendas_online.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     str
 1   Cliente          20 non-null     str
 2   Valor da compra  20 non-null     float64
dtypes: float64(1), str(2)
memory usage: 612.0 bytes

In [8]:
df_vendas_online

   Data de venda             Cliente  Valor da compra
0     06/06/2022     @ANA _LUCIA 321           836.50
1     06/06/2022  DieGO ARMANDIU 210           573.33
2     06/06/2022  DieGO ARMANDIU 210           392.80
3     06/06/2022  DieGO ARMANDIU 210           512.34
4     07/06/2022  Isabely JOanes 738           825.31
5     07/06/2022  Isabely JOanes 738           168.07
6     07/06/2022  Isabely JOanes 738           339.18
7     07/06/2022  Isabely JOanes 738           314.69
8     08/06/2022  Isabely JOanes 738           682.05
9     08/06/2022    JOãO Gabriel 671           386.34
10    08/06/2022  Julya meireles 914           622.65
11    08/06/2022  Julya meireles 914           630.79
12    09/06/2022  Julya meireles 914           390.30
13    09/06/2022     MaRIA Julia 444           759.16
14    09/06/2022     MaRIA Julia 444           334.47
15    09/06/2022     MaRIA Julia 444           678.78
16    10/06/2022     MaRIA Julia 444           314.24
17    10/06/2022     PEDRO PASCO 812           311.15
18    10/06/2022    Paulo castro 481           899.16
19    10/06/2022   Thiago fritzz 883           885.24

In [9]:
# Etapa 3: Na etapa 2, trabalhamos na transformação dos dados numéricos. Agora, podemos trabalhar com valores textuais.

# Devido a uma instabilidade no site da empresa, tivemos problemas com os nomes dos clientes durante o salvamento. Isso resultou em uma coluna de nomes de clientes com uma mistura de letras, maiúsculas e minúsculas, números e outros caracteres.

# Sabendo disso, manipule os textos presentes na coluna Cliente para que seja obtido como resultado os nomes dos clientes em letras minúsculas, com a ausência de caracteres especiais ou números.
df_vendas_online['Cliente'] = df_vendas_online['Cliente'].str.lower()

df_vendas_online['Cliente'] = df_vendas_online['Cliente'].str.replace('[^a-z ]', ' ', regex = True)
df_vendas_online

   Data de venda             Cliente  Valor da compra
0     06/06/2022      ana  lucia               836.50
1     06/06/2022  diego armandiu               573.33
2     06/06/2022  diego armandiu               392.80
3     06/06/2022  diego armandiu               512.34
4     07/06/2022  isabely joanes               825.31
5     07/06/2022  isabely joanes               168.07
6     07/06/2022  isabely joanes               339.18
7     07/06/2022  isabely joanes               314.69
8     08/06/2022  isabely joanes               682.05
9     08/06/2022    jo o gabriel               386.34
10    08/06/2022  julya meireles               622.65
11    08/06/2022  julya meireles               630.79
12    09/06/2022  julya meireles               390.30
13    09/06/2022     maria julia               759.16
14    09/06/2022     maria julia               334.47
15    09/06/2022     maria julia               678.78
16    10/06/2022     maria julia               314.24
17    10/06/2022     pedro pasco               311.15
18    10/06/2022    paulo castro               899.16
19    10/06/2022   thiago fritzz               885.24

In [10]:
# Etapa 4: Nas etapas anteriores, já trabalhamos com vários tipos de dados, agora podemos trabalhar com os dados de tempo.

# Na coluna Data de venda, temos datas em formato 'dia/mês/ano' (dd/mm/AAAA). Transforme esses dados para o tipo datetime e busque uma forma de visualização de subconjunto que possa contribuir no objetivo do contexto que os dados estão inseridos.

In [11]:
df_vendas_online['Data de venda'] = pd.to_datetime(df_vendas_online['Data de venda'], format ='%d/%m/%Y')

subset_clientes = df_vendas_online.groupby(['Cliente'])['Valor da compra'].sum()
subset_clientes

Cliente
 ana  lucia            836.50
diego armandiu        1478.47
isabely joanes        2329.30
jo o gabriel           386.34
julya meireles        1643.74
maria julia           2086.65
paulo castro           899.16
pedro pasco            311.15
thiago fritzz          885.24
Name: Valor da compra, dtype: float64

# Desafio 2
A administração de condomínios é uma tarefa que requer muita atenção e organização. Entre as diversas responsabilidades da gestão está o recebimento dos aluguéis dos locatários. Para garantir uma boa saúde financeira do empreendimento, é fundamental que esses pagamentos sejam feitos de forma regular e pontual. No entanto, sabemos que nem sempre isso acontece.

Pensando nisso, proponho um desafio de tratamento de dados com o objetivo de analisar o atraso no pagamento de aluguéis no condomínio de alguns moradores. Disponibilizo a base de dados dados_locacao_imoveis.json, que contém informações sobre o apartamento dos locatários, o dia acordado para o pagamento do aluguel, o dia da efetivação do pagamento de aluguel e o valor do aluguel.

Com essas informações, o desafio do projeto 2: administração de condomínios será similar ao desafio do projeto 1, abrir a base de dados com Pandas e aplicar o json_normalize no DataFrame.

In [12]:
# Pensando nisso, proponho um desafio de tratamento de dados com o objetivo de analisar o atraso no pagamento de aluguéis no condomínio de alguns moradores. Disponibilizo a base de dados dados_locacao_imoveis.json, que contém informações sobre o apartamento dos locatários, o dia acordado para o pagamento do aluguel, o dia da efetivação do pagamento de aluguel e o valor do aluguel.

# Com essas informações, o desafio do projeto 2: administração de condomínios será similar ao desafio do projeto 1, abrir a base de dados com Pandas e aplicar o json_normalize no DataFrame.

df_locacao_imoveis = pd.read_json('dados_locacao_imoveis.json')
df_locacao_imoveis = pd.json_normalize(df_locacao_imoveis['dados_locacao'])
df_locacao_imoveis

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),"[01/06/2022, 01/07/2022]","[05/06/2022, 03/07/2022]","[$ 1000,0 reais, $ 2500,0 reais]"
1,A102 (blocoAP),"[02/06/2022, 02/07/2022]","[02/06/2022, 06/07/2022]","[$ 1100,0 reais, $ 2600,0 reais]"
2,B201 (blocoAP),"[03/06/2022, 03/07/2022]","[07/06/2022, 03/07/2022]","[$ 1200,0 reais, $ 2700,0 reais]"
3,B202 (blocoAP),"[04/06/2022, 04/07/2022]","[07/06/2022, 05/07/2022]","[$ 1300,0 reais, $ 2800,0 reais]"
4,C301 (blocoAP),"[05/06/2022, 05/07/2022]","[10/06/2022, 09/07/2022]","[$ 1400,0 reais, $ 2900,0 reais]"
5,C302 (blocoAP),"[06/06/2022, 06/07/2022]","[08/06/2022, 12/07/2022]","[$ 1500,0 reais, $ 1200,0 reais]"
6,D401 (blocoAP),"[07/06/2022, 07/07/2022]","[07/06/2022, 09/07/2022]","[$ 1600,0 reais, $ 1300,0 reais]"
7,D402 (blocoAP),"[08/06/2022, 08/07/2022]","[10/06/2022, 14/07/2022]","[$ 1700,0 reais, $ 1400,0 reais]"
8,E501 (blocoAP),"[09/06/2022, 09/07/2022]","[10/06/2022, 09/07/2022]","[$ 1800,0 reais, $ 1500,0 reais]"
9,E502 (blocoAP),"[10/06/2022, 10/07/2022]","[16/06/2022, 12/07/2022]","[$ 1900,0 reais, $ 1600,0 reais]"
10,F601 (blocoAP),"[11/06/2022, 11/07/2022]","[17/06/2022, 13/07/2022]","[$ 2000,0 reais, $ 1000,0 reais]"
11,F602 (blocoAP),"[12/06/2022, 12/07/2022]","[15/06/2022, 12/07/2022]","[$ 2100,0 reais, $ 1100,0 reais]"
12,G701 (blocoAP),"[13/06/2022, 13/07/2022]","[19/06/2022, 20/07/2022]","[$ 2200,0 reais, $ 1200,0 reais]"
13,G702 (blocoAP),"[14/06/2022, 14/07/2022]","[15/06/2022, 17/07/2022]","[$ 2300,0 reais, $ 2100,0 reais]"
14,H801 (blocoAP),"[15/06/2022, 15/07/2022]","[18/06/2022, 16/07/2022]","[$ 2400,0 reais, $ 2200,0 reais]"

In [13]:
# Etapa 2: 

# Remover os dados em listas dentro do DataFrame;
# Verificar os tipos de dados;
# Identificar colunas numéricas;
# Transformar a coluna numérica para o tipo numérico.

In [14]:
colunas_locacao = list(df_locacao_imoveis.columns)
colunas_locacao

['apartamento',
 'datas_combinadas_pagamento',
 'datas_de_pagamento',
 'valor_aluguel']

In [15]:
df_locacao_imoveis = df_locacao_imoveis.explode(colunas_locacao[1:])
df_locacao_imoveis.reset_index(drop = True, inplace = True)
df_locacao_imoveis

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,"$ 1000,0 reais"
1,A101 (blocoAP),01/07/2022,03/07/2022,"$ 2500,0 reais"
2,A102 (blocoAP),02/06/2022,02/06/2022,"$ 1100,0 reais"
3,A102 (blocoAP),02/07/2022,06/07/2022,"$ 2600,0 reais"
4,B201 (blocoAP),03/06/2022,07/06/2022,"$ 1200,0 reais"
5,B201 (blocoAP),03/07/2022,03/07/2022,"$ 2700,0 reais"
6,B202 (blocoAP),04/06/2022,07/06/2022,"$ 1300,0 reais"
7,B202 (blocoAP),04/07/2022,05/07/2022,"$ 2800,0 reais"
8,C301 (blocoAP),05/06/2022,10/06/2022,"$ 1400,0 reais"
9,C301 (blocoAP),05/07/2022,09/07/2022,"$ 2900,0 reais"
10,C302 (blocoAP),06/06/2022,08/06/2022,"$ 1500,0 reais"
11,C302 (blocoAP),06/07/2022,12/07/2022,"$ 1200,0 reais"
12,D401 (blocoAP),07/06/2022,07/06/2022,"$ 1600,0 reais"
13,D401 (blocoAP),07/07/2022,09/07/2022,"$ 1300,0 reais"
14,D402 (blocoAP),08/06/2022,10/06/2022,"$ 1700,0 reais"
15,D402 (blocoAP),08/07/2022,14/07/2022,"$ 1400,0 reais"
16,E501 (blocoAP),09/06/2022,10/06/2022,"$ 1800,0 reais"
17,E501 (blocoAP),09/07/2022,09/07/2022,"$ 1500,0 reais"
18,E502 (blocoAP),10/06/2022,16/06/2022,"$ 1900,0 reais"
19,E502 (blocoAP),10/07/2022,12/07/2022,"$ 1600,0 reais"
20,F601 (blocoAP),11/06/2022,17/06/2022,"$ 2000,0 reais"
21,F601 (blocoAP),11/07/2022,13/07/2022,"$ 1000,0 reais"
22,F602 (blocoAP),12/06/2022,15/06/2022,"$ 2100,0 reais"
23,F602 (blocoAP),12/07/2022,12/07/2022,"$ 1100,0 reais"
24,G701 (blocoAP),13/06/2022,19/06/2022,"$ 2200,0 reais"
25,G701 (blocoAP),13/07/2022,20/07/2022,"$ 1200,0 reais"
26,G702 (blocoAP),14/06/2022,15/06/2022,"$ 2300,0 reais"
27,G702 (blocoAP),14/07/2022,17/07/2022,"$ 2100,0 reais"
28,H801 (blocoAP),15/06/2022,18/06/2022,"$ 2400,0 reais"
29,H801 (blocoAP),15/07/2022,16/07/2022,"$ 2200,0 reais"

In [16]:
df_locacao_imoveis.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     str
 1   datas_combinadas_pagamento  30 non-null     str
 2   datas_de_pagamento          30 non-null     str
 3   valor_aluguel               30 non-null     str
dtypes: str(4)
memory usage: 1.1 KB

In [17]:
df_locacao_imoveis['valor_aluguel'] = df_locacao_imoveis['valor_aluguel'].apply(lambda x: x.replace('$', '').replace('reais', '').replace(',', '.').strip())
df_locacao_imoveis

       apartamento datas_combinadas_pagamento datas_de_pagamento valor_aluguel
0   A101 (blocoAP)                 01/06/2022         05/06/2022        1000.0
1   A101 (blocoAP)                 01/07/2022         03/07/2022        2500.0
2   A102 (blocoAP)                 02/06/2022         02/06/2022        1100.0
3   A102 (blocoAP)                 02/07/2022         06/07/2022        2600.0
4   B201 (blocoAP)                 03/06/2022         07/06/2022        1200.0
5   B201 (blocoAP)                 03/07/2022         03/07/2022        2700.0
6   B202 (blocoAP)                 04/06/2022         07/06/2022        1300.0
7   B202 (blocoAP)                 04/07/2022         05/07/2022        2800.0
8   C301 (blocoAP)                 05/06/2022         10/06/2022        1400.0
9   C301 (blocoAP)                 05/07/2022         09/07/2022        2900.0
10  C302 (blocoAP)                 06/06/2022         08/06/2022        1500.0
11  C302 (blocoAP)                 06/07/2022         12/07/2022        1200.0
12  D401 (blocoAP)                 07/06/2022         07/06/2022        1600.0
13  D401 (blocoAP)                 07/07/2022         09/07/2022        1300.0
14  D402 (blocoAP)                 08/06/2022         10/06/2022        1700.0
15  D402 (blocoAP)                 08/07/2022         14/07/2022        1400.0
16  E501 (blocoAP)                 09/06/2022         10/06/2022        1800.0
17  E501 (blocoAP)                 09/07/2022         09/07/2022        1500.0
18  E502 (blocoAP)                 10/06/2022         16/06/2022        1900.0
19  E502 (blocoAP)                 10/07/2022         12/07/2022        1600.0
20  F601 (blocoAP)                 11/06/2022         17/06/2022        2000.0
21  F601 (blocoAP)                 11/07/2022         13/07/2022        1000.0
22  F602 (blocoAP)                 12/06/2022         15/06/2022        2100.0
23  F602 (blocoAP)                 12/07/2022         12/07/2022        1100.0
24  G701 (blocoAP)                 13/06/2022         19/06/2022        2200.0
25  G701 (blocoAP)                 13/07/2022         20/07/2022        1200.0
26  G702 (blocoAP)                 14/06/2022         15/06/2022        2300.0
27  G702 (blocoAP)                 14/07/2022         17/07/2022        2100.0
28  H801 (blocoAP)                 15/06/2022         18/06/2022        2400.0
29  H801 (blocoAP)                 15/07/2022         16/07/2022        2200.0

In [18]:
df_locacao_imoveis['valor_aluguel'] = df_locacao_imoveis['valor_aluguel'].astype(np.float64)
df_locacao_imoveis.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     str
 1   datas_combinadas_pagamento  30 non-null     str
 2   datas_de_pagamento          30 non-null     str
 3   valor_aluguel               30 non-null     float64
dtypes: float64(1), str(3)
memory usage: 1.1 KB

In [19]:
# Etapa 3: Na etapa 2, trabalhamos na transformação dos dados numéricos. Agora, podemos trabalhar com valores textuais.

# Buscando explicar a organização da identificação dos apartamentos, durante a criação do conjunto de dados, foi adicionado o texto (blocoAP). Esse texto informa que os nomes dos apartamentos estão organizados com a letra do bloco seguida do número do apartamento. No entanto, isso não traz nenhuma informação para nossos dados, sendo interessante realizar a remoção desse texto no conjunto de dados.

# Com isso, manipule os textos na coluna apartamento para remover o texto (blocoAP) do DataFrame.

df_locacao_imoveis['apartamento'] = df_locacao_imoveis['apartamento'].str.replace(' (blocoAP)', '')
df_locacao_imoveis.head()

  apartamento datas_combinadas_pagamento datas_de_pagamento  valor_aluguel
0        A101                 01/06/2022         05/06/2022         1000.0
1        A101                 01/07/2022         03/07/2022         2500.0
2        A102                 02/06/2022         02/06/2022         1100.0
3        A102                 02/07/2022         06/07/2022         2600.0
4        B201                 03/06/2022         07/06/2022         1200.0

In [20]:
# Nas colunas datas_de_pagamento e datas_combinadas_pagamento, temos datas em formato 'dia/mês/ano' (dd/mm/AAAA). Transforme esses dados para o tipo datetime e busque uma forma de visualização de subconjunto que possa contribuir no objetivo do contexto que os dados estão inseridos.

In [21]:
df_locacao_imoveis['datas_combinadas_pagamento'] = pd.to_datetime(df_locacao_imoveis['datas_combinadas_pagamento'], format = '%d/%m/%Y')
df_locacao_imoveis['datas_de_pagamento'] = pd.to_datetime(df_locacao_imoveis['datas_de_pagamento'], format = '%d/%m/%Y')
df_locacao_imoveis

   apartamento datas_combinadas_pagamento datas_de_pagamento  valor_aluguel
0         A101                 2022-06-01         2022-06-05         1000.0
1         A101                 2022-07-01         2022-07-03         2500.0
2         A102                 2022-06-02         2022-06-02         1100.0
3         A102                 2022-07-02         2022-07-06         2600.0
4         B201                 2022-06-03         2022-06-07         1200.0
5         B201                 2022-07-03         2022-07-03         2700.0
6         B202                 2022-06-04         2022-06-07         1300.0
7         B202                 2022-07-04         2022-07-05         2800.0
8         C301                 2022-06-05         2022-06-10         1400.0
9         C301                 2022-07-05         2022-07-09         2900.0
10        C302                 2022-06-06         2022-06-08         1500.0
11        C302                 2022-07-06         2022-07-12         1200.0
12        D401                 2022-06-07         2022-06-07         1600.0
13        D401                 2022-07-07         2022-07-09         1300.0
14        D402                 2022-06-08         2022-06-10         1700.0
15        D402                 2022-07-08         2022-07-14         1400.0
16        E501                 2022-06-09         2022-06-10         1800.0
17        E501                 2022-07-09         2022-07-09         1500.0
18        E502                 2022-06-10         2022-06-16         1900.0
19        E502                 2022-07-10         2022-07-12         1600.0
20        F601                 2022-06-11         2022-06-17         2000.0
21        F601                 2022-07-11         2022-07-13         1000.0
22        F602                 2022-06-12         2022-06-15         2100.0
23        F602                 2022-07-12         2022-07-12         1100.0
24        G701                 2022-06-13         2022-06-19         2200.0
25        G701                 2022-07-13         2022-07-20         1200.0
26        G702                 2022-06-14         2022-06-15         2300.0
27        G702                 2022-07-14         2022-07-17         2100.0
28        H801                 2022-06-15         2022-06-18         2400.0
29        H801                 2022-07-15         2022-07-16         2200.0

In [23]:
df_locacao_imoveis['atraso'] = (df_locacao_imoveis['datas_de_pagamento'] - df_locacao_imoveis['datas_combinadas_pagamento']).dt.days
df_locacao_imoveis

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel,atraso
0,A101,2022-06-01,2022-06-05,1000.0,4
1,A101,2022-07-01,2022-07-03,2500.0,2
2,A102,2022-06-02,2022-06-02,1100.0,0
3,A102,2022-07-02,2022-07-06,2600.0,4
4,B201,2022-06-03,2022-06-07,1200.0,4
5,B201,2022-07-03,2022-07-03,2700.0,0
6,B202,2022-06-04,2022-06-07,1300.0,3
7,B202,2022-07-04,2022-07-05,2800.0,1
8,C301,2022-06-05,2022-06-10,1400.0,5
9,C301,2022-07-05,2022-07-09,2900.0,4
10,C302,2022-06-06,2022-06-08,1500.0,2
11,C302,2022-07-06,2022-07-12,1200.0,6
12,D401,2022-06-07,2022-06-07,1600.0,0
13,D401,2022-07-07,2022-07-09,1300.0,2
14,D402,2022-06-08,2022-06-10,1700.0,2
15,D402,2022-07-08,2022-07-14,1400.0,6
16,E501,2022-06-09,2022-06-10,1800.0,1
17,E501,2022-07-09,2022-07-09,1500.0,0
18,E502,2022-06-10,2022-06-16,1900.0,6
19,E502,2022-07-10,2022-07-12,1600.0,2
20,F601,2022-06-11,2022-06-17,2000.0,6
21,F601,2022-07-11,2022-07-13,1000.0,2
22,F602,2022-06-12,2022-06-15,2100.0,3
23,F602,2022-07-12,2022-07-12,1100.0,0
24,G701,2022-06-13,2022-06-19,2200.0,6
25,G701,2022-07-13,2022-07-20,1200.0,7
26,G702,2022-06-14,2022-06-15,2300.0,1
27,G702,2022-07-14,2022-07-17,2100.0,3
28,H801,2022-06-15,2022-06-18,2400.0,3
29,H801,2022-07-15,2022-07-16,2200.0,1

In [25]:
media_atraso = df_locacao_imoveis.groupby(['apartamento'])['atraso'].mean()
media_atraso

apartamento
A101    3.0
A102    2.0
B201    2.0
B202    2.0
C301    4.5
C302    4.0
D401    1.0
D402    4.0
E501    0.5
E502    4.0
F601    4.0
F602    1.5
G701    6.5
G702    2.0
H801    2.0
Name: atraso, dtype: float64